### PR TITLE
Design changes

### PR DESCRIPTION
**Pull request by lthamm**
Suggestion to restructure the design:

Clear up room by adding the logo to the main nav
Adding CTAs to index
Introducing primary color
Grey background and white elements to better integrate with cards

### CODE REVIEW

**Comment by bartrail** [comment]
I like the idea for the landing page and the navigation.
But I have a few things to point out, that I see different:
* the primary color (red) is associated with healthcare (like in the red cross) so I think we should stick to that and use these for all call-of-actions and keep using it on the map.
* What is unclear to me then, is if every call-to-action has the same color. in the current layout, the "healthcare-call-to-action" is "red" and the "maker-call-to-action" is "green" - maybe this could be unified?
* Is it intentional or a bug that the navigation is on top of the modals (in z-index order)? Headlines in modals appear behind the navigation, so they all should either be put down a bit or the navigation should be placed "behind" the modals
* The landing-page styling with the card-layout and shadows could be re-used throughout other page elements as well to keep it consistent

Any other thoughts?

**Comment by lthamm** [comment]
> * The landing-page styling with the card-layout and shadows could be re-used throughout other page elements as well to keep it consistent

I already did that on multiple other pages (FAQ, Data privacy...), but I made it reusable, so we can use it for anything. I think it would be especially nice to integrate it with the thinglist, but that could also be merged later on.

> * Is it intentional or a bug that the navigation is on top of the modals (in z-index order)? Headlines in modals appear behind the navigation, so they all should either be put down a bit or the navigation should be placed "behind" the modals

I haven't made any changes to z-indexes (because bootstrap would automatically put the modals on top). Have there been any custom changes before? Maybe I removed a custom class that handled this.. How can I trigger a modal to check this?


> * What is unclear to me then, is if every call-to-action has the same color. in the current layout, the "healthcare-call-to-action" is "red" and the "maker-call-to-action" is "green" - maybe this could be unified?

That was somewhat the idea, to visually separate makers (green: "i can provide") from healthcare (red: " i need") if those two things are already on the same page, which I wouldnt consider to be optimal in the long term. But maybe it would be better to keep this consistent first and do this more thorough later on.


> * the primary color (red) is associated with healthcare (like in the red cross) so I think we should stick to that and use these for all call-of-actions and keep using it on the map.

True. Red is also associated with urgency (which is also true in this case) and is quite alarming. Most health care providers utilise green and or blue to signal calmness and aid, which is the mission of p4h as well. Even the red cross limits the use of red and complements it with a lot of blue: https://www.drk.de.


So todo for now:
* Fix modals z-index
* Uniform cta colors

To be discussed:
* What shall the primary cta color be? Red or blue (or something entirely new)?

**Comment by bartrail** [comment]
> I haven't made any changes to z-indexes (because bootstrap would automatically put the modals on top). Have there been any custom changes before? Maybe I removed a custom class that handled this.. How can I trigger a modal to check this?

The Login modal for example :)

> 
> * Fix modals z-index
> * Uniform cta colors
👍 
> 
> To be discussed:
> 
> * What shall the primary cta color be? Red or blue (or something entirely new)?

👍We'll discuss that in our #design slack-channel

**Comment by bartrail** [comment]
closing for now as we are re-evaluating the strategy after print4health.

**Pull request closed without merging**
