### PR TITLE
feature/hubs

### LINKED ISSUE #209: Add Hubs for logistic as they are organized in #MakerVsVirus
extend requester entity with `isHub` and `area`-geo-polygone data to be able to showcase thigns

### PR DESCRIPTION
**Pull request by gherkins**
activate the following view via `<IndexMap />`

Bildschirmfoto 2020-03-29 um 15 29 33

### CODE REVIEW

**Comment by bartrail** [comment]
When Requester Registration #140 is finished, this can be enhanced for this as well.. what about the polys then? 🤔

**Comment by gherkins** [comment]
activate via `<IndexMap />`

**Comment by gherkins** [comment]
> When Requester Registration #140 is finished, this can be enhanced for this as well.. what about the polys then? 🤔

would work fine without in a first version

**Review by bartrail — APPROVED** [review]
nice

**Pull request merged**
